services:
  # 数据库初始化统一由 Prisma migration + seed 负责
  db-init:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: backend-build
    environment:
      DATABASE_URL: "postgresql://jobtap:jobtap@123.@postgres:5432/jobtap-admin-base-backend?schema=public"
      DIRECT_DATABASE_URL: "postgresql://jobtap:jobtap@123.@postgres:5432/jobtap-admin-base-backend?schema=public"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        ./node_modules/.bin/prisma migrate deploy --schema prisma/schema.prisma &&
        ./node_modules/.bin/prisma db seed
      "
    networks:
      - jobtap-admin-base

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    # image: jobtap-admin-base-backend:0.0.1
    environment:
      TZ: Asia/Shanghai
      CASBIN_MODEL: "model.conf"
      NODE_ENV: production
      APP_PORT: 9528
      DOC_SWAGGER_ENABLE: "true"
      DOC_SWAGGER_PATH: "api-docs"
      DATABASE_URL: "postgresql://jobtap:jobtap@123.@postgres:5432/jobtap-admin-base-backend?schema=public"
      DIRECT_DATABASE_URL: "postgresql://jobtap:jobtap@123.@postgres:5432/jobtap-admin-base-backend?schema=public"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      REDIS_PASSWORD: "123456"
      REDIS_DB: 1
      JWT_SECRET: "JWT_SECRET-jobtap-admin-base@123456!@#."
      JWT_EXPIRE_IN: 3600
      REFRESH_TOKEN_SECRET: "REFRESH_TOKEN_EXPIRE_IN-jobtap-admin-base@123456!@#."
      REFRESH_TOKEN_EXPIRE_IN: 7200
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully
    ports:
      - "9528:9528"
    networks:
      - jobtap-admin-base
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://backend:9528/v1/route/getConstantRoutes"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    cpus: 2

  postgres:
    image: postgres:16.3
    environment:
      TZ: Asia/Shanghai
      POSTGRES_PASSWORD: jobtap@123.
      POSTGRES_USER: jobtap
      POSTGRES_DB: jobtap-admin-base-backend
    ports:
      - "25432:5432"
    volumes:
      - jobtap-admin-base-postgres_data:/usr/share/docker/postgresql
    networks:
      - jobtap-admin-base
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobtap -d jobtap-admin-base-backend"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack:7.2.0-v11
    environment:
      TZ: Asia/Shanghai
    command: redis-server --requirepass 123456
    ports:
      - "26379:6379"
    volumes:
      - jobtap-admin-base-redis_data:/data
    networks:
      - jobtap-admin-base
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "123456", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  jobtap-admin-base-postgres_data:
  jobtap-admin-base-redis_data:

networks:
  jobtap-admin-base:
