services:
  postgres:
    image: postgres:16.3
    environment:
      TZ: Asia/Shanghai
      POSTGRES_PASSWORD: jobtap@123.
      POSTGRES_USER: jobtap
      POSTGRES_DB: jobtap-admin-base-backend
    ports:
      - "25432:5432"
    volumes:
      - jobtap-admin-base-postgres_data:/var/lib/postgresql/data
    networks:
      - jobtap-admin-base
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobtap -d jobtap-admin-base-backend"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack:7.2.0-v11
    environment:
      TZ: Asia/Shanghai
    command: redis-server --requirepass 123456
    ports:
      - "26379:6379"
    volumes:
      - jobtap-admin-base-redis_data:/data
    networks:
      - jobtap-admin-base
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "123456", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  jobtap-admin-base-postgres_data:
  jobtap-admin-base-redis_data:

networks:
  jobtap-admin-base: