/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "access-key": () => import("@/views/access-key/index.vue"),
  home: () => import("@/views/home/index.vue"),
  log_login: () => import("@/views/log/login/index.vue"),
  log_operation: () => import("@/views/log/operation/index.vue"),
  platform_audit: () => import("@/views/platform/audit/index.vue"),
  platform_capability: () => import("@/views/platform/capability/index.vue"),
  "platform_resource-catalog": () => import("@/views/platform/resource-catalog/index.vue"),
  "platform_role-template": () => import("@/views/platform/role-template/index.vue"),
  platform_tenant: () => import("@/views/platform/tenant/index.vue"),
  tenant_audit: () => import("@/views/tenant/audit/index.vue"),
  tenant_role: () => import("@/views/tenant/role/index.vue"),
  "tenant_user-auth-profile": () => import("@/views/tenant/user-auth-profile/index.vue"),
  tenant_user: () => import("@/views/tenant/user/index.vue"),
};
