/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'access-key',
    path: '/access-key',
    component: 'layout.base$view.access-key',
    meta: {
      title: 'access-key',
      i18nKey: 'route.access-key'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'log',
    path: '/log',
    component: 'layout.base',
    meta: {
      title: 'log',
      i18nKey: 'route.log'
    },
    children: [
      {
        name: 'log_login',
        path: '/log/login',
        component: 'view.log_login',
        meta: {
          title: 'log_login',
          i18nKey: 'route.log_login'
        }
      },
      {
        name: 'log_operation',
        path: '/log/operation',
        component: 'view.log_operation',
        meta: {
          title: 'log_operation',
          i18nKey: 'route.log_operation'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'platform',
    path: '/platform',
    component: 'layout.base',
    meta: {
      title: 'platform',
      i18nKey: 'route.platform'
    },
    children: [
      {
        name: 'platform_audit',
        path: '/platform/audit',
        component: 'view.platform_audit',
        meta: {
          title: 'platform_audit',
          i18nKey: 'route.platform_audit'
        }
      },
      {
        name: 'platform_capability',
        path: '/platform/capability',
        component: 'view.platform_capability',
        meta: {
          title: 'platform_capability',
          i18nKey: 'route.platform_capability'
        }
      },
      {
        name: 'platform_resource-catalog',
        path: '/platform/resource-catalog',
        component: 'view.platform_resource-catalog',
        meta: {
          title: 'platform_resource-catalog',
          i18nKey: 'route.platform_resource-catalog'
        }
      },
      {
        name: 'platform_role-template',
        path: '/platform/role-template',
        component: 'view.platform_role-template',
        meta: {
          title: 'platform_role-template',
          i18nKey: 'route.platform_role-template'
        }
      },
      {
        name: 'platform_tenant',
        path: '/platform/tenant',
        component: 'view.platform_tenant',
        meta: {
          title: 'platform_tenant',
          i18nKey: 'route.platform_tenant'
        }
      }
    ]
  },
  {
    name: 'tenant',
    path: '/tenant',
    component: 'layout.base',
    meta: {
      title: 'tenant',
      i18nKey: 'route.tenant'
    },
    children: [
      {
        name: 'tenant_audit',
        path: '/tenant/audit',
        component: 'view.tenant_audit',
        meta: {
          title: 'tenant_audit',
          i18nKey: 'route.tenant_audit'
        }
      },
      {
        name: 'tenant_user',
        path: '/tenant/user',
        component: 'view.tenant_user',
        meta: {
          title: 'tenant_user',
          i18nKey: 'route.tenant_user'
        }
      },
      {
        name: 'tenant_role',
        path: '/tenant/role',
        component: 'view.tenant_role',
        meta: {
          title: 'tenant_role',
          i18nKey: 'route.tenant_role'
        }
      },
      {
        name: 'tenant_user-auth-profile',
        path: '/tenant/user-auth-profile',
        component: 'view.tenant_user-auth-profile',
        meta: {
          title: 'tenant_user-auth-profile',
          i18nKey: 'route.tenant_user-auth-profile'
        }
      }
    ]
  }
];

