import { Prisma } from '@prisma/client';

import { prisma } from '../helper';

export const initSysMenu = async () => {
  const data: Prisma.SysMenuCreateManyInput[] = [
    { id: 1, menuType: 'menu', menuName: 'login', iconType: 1, icon: null, routeName: 'login', routePath: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?', component: 'layout.blank$view.login', pathParam: null, status: 'ENABLED', activeMenu: null, hideInMenu: true, pid: 0, order: 0, i18nKey: 'route.login', keepAlive: false, constant: true, href: null, multiTab: false, createdBy: '-1', updatedAt: null, updatedBy: null },
    { id: 2, menuType: 'menu', menuName: '403', iconType: 1, icon: null, routeName: '403', routePath: '/403', component: 'layout.blank$view.403', pathParam: null, status: 'ENABLED', activeMenu: null, hideInMenu: true, pid: 0, order: 0, i18nKey: 'route.403', keepAlive: false, constant: true, href: null, multiTab: false, createdBy: '-1', updatedAt: null, updatedBy: null },
    { id: 3, menuType: 'menu', menuName: '404', iconType: 1, icon: null, routeName: '404', routePath: '/404', component: 'layout.blank$view.404', pathParam: null, status: 'ENABLED', activeMenu: null, hideInMenu: true, pid: 0, order: 0, i18nKey: 'route.404', keepAlive: false, constant: true, href: null, multiTab: false, createdBy: '-1', updatedAt: null, updatedBy: null },
    { id: 4, menuType: 'menu', menuName: '500', iconType: 1, icon: null, routeName: '500', routePath: '/500', component: 'layout.blank$view.500', pathParam: null, status: 'ENABLED', activeMenu: null, hideInMenu: true, pid: 0, order: 0, i18nKey: 'route.500', keepAlive: false, constant: true, href: null, multiTab: false, createdBy: '-1', updatedAt: null, updatedBy: null },
    { id: 5, menuType: 'menu', menuName: 'iframe-page', iconType: 1, icon: null, routeName: 'iframe-page', routePath: '/iframe-page/:url', component: 'layout.base$view.iframe-page', pathParam: null, status: 'ENABLED', activeMenu: null, hideInMenu: true, pid: 0, order: 0, i18nKey: 'route.iframe-page', keepAlive: false, constant: true, href: null, multiTab: false, createdBy: '-1', updatedAt: null, updatedBy: null },
    { id: 50, menuType: 'menu', menuName: 'home', iconType: 1, icon: 'mdi:monitor-dashboard', routeName: 'home', routePath: '/home', component: 'layout.base$view.home', pathParam: null, status: 'ENABLED', activeMenu: null, hideInMenu: false, pid: 0, order: 0, i18nKey: 'route.home', keepAlive: false, constant: false, href: null, multiTab: false, createdBy: '-1', updatedAt: null, updatedBy: null },
    { id: 100, menuType: 'directory', menuName: '平台管理', iconType: 1, icon: 'carbon:cloud-service-management', routeName: 'platform', routePath: '/platform', component: 'layout.base', pathParam: null, status: 'ENABLED', activeMenu: null, hideInMenu: false, pid: 0, order: 10, i18nKey: 'route.platform', keepAlive: false, constant: false, href: null, multiTab: false, createdBy: '-1', updatedAt: null, updatedBy: null },
    { id: 101, menuType: 'menu', menuName: '租户管理', iconType: 1, icon: 'mdi:domain', routeName: 'platform_tenant', routePath: '/platform/tenant', component: 'view.platform_tenant', pathParam: null, status: 'ENABLED', activeMenu: null, hideInMenu: false, pid: 100, order: 0, i18nKey: 'route.platform_tenant', keepAlive: false, constant: false, href: null, multiTab: false, createdBy: '-1', updatedAt: null, updatedBy: null },
    { id: 102, menuType: 'menu', menuName: '角色模板', iconType: 1, icon: 'carbon:user-role', routeName: 'platform_role-template', routePath: '/platform/role-template', component: 'view.platform_role-template', pathParam: null, status: 'ENABLED', activeMenu: null, hideInMenu: false, pid: 100, order: 1, i18nKey: 'route.platform_role-template', keepAlive: false, constant: false, href: null, multiTab: false, createdBy: '-1', updatedAt: null, updatedBy: null },
    { id: 103, menuType: 'menu', menuName: '能力目录', iconType: 1, icon: 'carbon:data-class', routeName: 'platform_capability', routePath: '/platform/capability', component: 'view.platform_capability', pathParam: null, status: 'ENABLED', activeMenu: null, hideInMenu: false, pid: 100, order: 2, i18nKey: 'route.platform_capability', keepAlive: false, constant: false, href: null, multiTab: false, createdBy: '-1', updatedAt: null, updatedBy: null },
    { id: 104, menuType: 'menu', menuName: '资源目录', iconType: 1, icon: 'material-symbols:route', routeName: 'platform_resource-catalog', routePath: '/platform/resource-catalog', component: 'view.platform_resource-catalog', pathParam: null, status: 'ENABLED', activeMenu: null, hideInMenu: false, pid: 100, order: 3, i18nKey: 'route.platform_resource-catalog', keepAlive: true, constant: false, href: null, multiTab: false, createdBy: '-1', updatedAt: null, updatedBy: null },
    { id: 105, menuType: 'menu', menuName: '平台审计', iconType: 1, icon: 'carbon:license-draft', routeName: 'platform_audit', routePath: '/platform/audit', component: 'view.platform_audit', pathParam: null, status: 'ENABLED', activeMenu: null, hideInMenu: false, pid: 100, order: 4, i18nKey: 'route.platform_audit', keepAlive: false, constant: false, href: null, multiTab: false, createdBy: '-1', updatedAt: null, updatedBy: null },
    { id: 200, menuType: 'directory', menuName: '租户管理', iconType: 1, icon: 'carbon:user-multiple', routeName: 'tenant', routePath: '/tenant', component: 'layout.base', pathParam: null, status: 'ENABLED', activeMenu: null, hideInMenu: false, pid: 0, order: 11, i18nKey: 'route.tenant', keepAlive: false, constant: false, href: null, multiTab: false, createdBy: '-1', updatedAt: null, updatedBy: null },
    { id: 201, menuType: 'menu', menuName: '用户管理', iconType: 1, icon: 'ic:round-manage-accounts', routeName: 'tenant_user', routePath: '/tenant/user', component: 'view.tenant_user', pathParam: null, status: 'ENABLED', activeMenu: null, hideInMenu: false, pid: 200, order: 0, i18nKey: 'route.tenant_user', keepAlive: false, constant: false, href: null, multiTab: false, createdBy: '-1', updatedAt: null, updatedBy: null },
    { id: 202, menuType: 'menu', menuName: '角色管理', iconType: 1, icon: 'carbon:user-role', routeName: 'tenant_role', routePath: '/tenant/role', component: 'view.tenant_role', pathParam: null, status: 'ENABLED', activeMenu: null, hideInMenu: false, pid: 200, order: 1, i18nKey: 'route.tenant_role', keepAlive: false, constant: false, href: null, multiTab: false, createdBy: '-1', updatedAt: null, updatedBy: null },
    { id: 203, menuType: 'menu', menuName: '用户授权档案', iconType: 1, icon: 'carbon:settings-check', routeName: 'tenant_user-auth-profile', routePath: '/tenant/user-auth-profile', component: 'view.tenant_user-auth-profile', pathParam: null, status: 'ENABLED', activeMenu: null, hideInMenu: false, pid: 200, order: 2, i18nKey: 'route.tenant_user-auth-profile', keepAlive: false, constant: false, href: null, multiTab: false, createdBy: '-1', updatedAt: null, updatedBy: null },
    { id: 204, menuType: 'menu', menuName: '租户审计', iconType: 1, icon: 'carbon:license-draft', routeName: 'tenant_audit', routePath: '/tenant/audit', component: 'view.tenant_audit', pathParam: null, status: 'ENABLED', activeMenu: null, hideInMenu: false, pid: 200, order: 3, i18nKey: 'route.tenant_audit', keepAlive: false, constant: false, href: null, multiTab: false, createdBy: '-1', updatedAt: null, updatedBy: null }
  ];

  return prisma.sysMenu.createMany({ data, skipDuplicates: true });
};
